import{a as p,S as d,i as a}from"./assets/vendor-C1DvvBV_.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&n(o)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const h="57544927-80e3a47216b97f3e9b612798b",g="https://pixabay.com/api/";function y(i){const s=new URLSearchParams({key:h,q:i,image_type:"photo",orientation:"horizontal",safesearch:"true"});return p.get(g,{params:s}).then(r=>r.data)}const l=document.querySelector(".gallery"),c=document.querySelector(".loader"),b=new d(".gallery a",{captionsData:"alt",captionDelay:250});function L(i){const s=i.map(({webformatURL:r,largeImageURL:n,tags:e,likes:t,views:o,comments:f,downloads:m})=>`<li class="gallery-item">
                <a class="gallery-link" href="${n}">
                    <img class="gallery-image" src="${r}" alt="${e}" />
                </a>
                <ul class="info-list">
                    <li class="info-item"><b>Likes</b> <span>${t}</span></li>
                    <li class="info-item"><b>Views</b> <span>${o}</span></li>
                    <li class="info-item"><b>Comments</b> <span>${f}</span></li>
                    <li class="info-item"><b>Downloads</b> <span>${m}</span></li>
                </ul>
            </li>`).join("");l.insertAdjacentHTML("beforeend",s),b.refresh()}function S(){l.innerHTML=""}function w(){c.classList.remove("is-hidden")}function P(){c.classList.add("is-hidden")}const u=document.querySelector(".form");u.addEventListener("submit",q);function q(i){i.preventDefault();const s=i.currentTarget.elements["search-text"].value.trim();if(!s){a.warning({message:"Please enter a search query!",position:"topRight"});return}S(),w(),y(s).then(r=>{if(!r.hits||r.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}L(r.hits)}).catch(r=>{a.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(r)}).finally(()=>{P(),u.reset()})}
//# sourceMappingURL=index.js.map
